[[redirects]]
from = "https://news.seanmilfort.com/*"
to = "https://seanmilfort.substack.com/"
status = 301
force = true
[[redirects]]
from = "https://www.news.seanmilfort.com/*"
to = "https://seanmilfort.substack.com/"
status = 301
force = true
[[redirects]]
from = "https://resume.seanmilfort.com/*"
to = "https://seanmilfort.com/Sean_Milfort_Resume.pdf"
status = 301
force = true